queries:
    all_epics_query:
        query_name: "All Epics"
        description: "Query to find all Epics that are not in 'Closed' or 'Removed' state."
        wiql: |
            SELECT
                [System.Id],
                [System.Title],
                [System.State]
            FROM
                WorkItems
            WHERE
                [System.WorkItemType] = 'Epic'
                AND [System.State] <> 'Closed'
                AND [System.State] <> 'Removed'
            ORDER BY [System.Id]